version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nova
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: novastream
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - db_data_ns6:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nova -d novastream"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks: [webnet]

  api:
    image: node:20-alpine
    init: true
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://nova:changeme@db:5432/novastream
      API_PORT: 4000
      NODE_ENV: production
      CORS_ORIGINS: https://app.lorna.tv
      COOKIE_DOMAIN: .lorna.tv
      COOKIE_SECURE: "true"
      COOKIE_SAMESITE: none
      TMDB_API_KEY: d8175301037c00f3c719478998396539
      API_JWT_SECRET: Y7dD6Vh2mC4pQ8tR1sX9zK3wL5aN0fB2gU4hJ6iO8lT1qP3dV
      API_REFRESH_SECRET: 9uU6sT4rQ2pO0nM7lK5jH3gF1dC9bA7Z5X3V1T
      API_JWT_ACCESS_TTL: "900"
      API_JWT_REFRESH_TTL: "1209600"
      API_ENCRYPTION_KEY: "a1b2c3d4e5f60718293a4bc5de6f70819a2b3c4d5e6f7a801f2e3d4c9b8a7c6d"
    command:
      - sh
      - -lc
      - |
        set -e
        apk add --no-cache unzip curl
        rm -rf /tmp/Nova-Stream-main /tmp/src.zip
        curl -L https://github.com/SaohTG/Nova-Stream/archive/refs/heads/main.zip -o /tmp/src.zip
        unzip -o -q /tmp/src.zip -d /tmp
        rm -rf /app/*
        cp -r /tmp/Nova-Stream-main/api/. /app
        npm ci || npm i
        npm run build
        node dist/main.js
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:'+(process.env.API_PORT||4000)+'/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 120s
    networks: [webnet]
    restart: unless-stopped

  web:
    image: node:20-alpine
    init: true
    working_dir: /app
    environment:
      VITE_API_BASE: /api
      NODE_ENV: production
      NPM_CONFIG_PRODUCTION: "false"
    command:
      - sh
      - -lc
      - |
        set -e
        apk add --no-cache unzip curl
        rm -rf /tmp/Nova-Stream-main /tmp/src.zip
        curl -L https://github.com/SaohTG/Nova-Stream/archive/refs/heads/main.zip -o /tmp/src.zip
        unzip -o -q /tmp/src.zip -d /tmp
        rm -rf /app/*
        cp -r /tmp/Nova-Stream-main/web/. /app
        npm ci || npm i
        npm run build
        npx serve -s dist -l 8081
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8081/ >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks: [webnet]
    restart: unless-stopped

volumes:
  db_data_ns6: {}

networks:
  webnet:
    driver: bridge
