version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - db_data_ns4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || pg_isready -U postgres -d postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 90s

  api:
    build:
      context: https://github.com/SaohTG/Nova-Stream.git#main:api   # <- contexte = dossier api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      API_PORT: ${API_PORT}
      API_JWT_ACCESS_TTL: ${API_JWT_ACCESS_TTL}
      API_JWT_REFRESH_TTL: ${API_JWT_REFRESH_TTL}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_REFRESH_SECRET: ${API_REFRESH_SECRET}
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
      TMDB_API_KEY: ${TMDB_API_KEY}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${API_PORT:-4000}:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: https://github.com/SaohTG/Nova-Stream.git#main:web   # <- contexte = dossier web
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://85.31.239.110:${API_PORT:-4000}
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data_ns4: {}
