version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run build && node dist/main.js"
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      API_PORT: ${API_PORT}
      API_JWT_ACCESS_TTL: ${API_JWT_ACCESS_TTL}
      API_JWT_REFRESH_TTL: ${API_JWT_REFRESH_TTL}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_REFRESH_SECRET: ${API_REFRESH_SECRET}
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
      TMDB_API_KEY: ${TMDB_API_KEY}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${API_PORT:-4000}:4000"
    volumes:
      - api_data:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run build && npm run preview -- --host 0.0.0.0 --port 5173"
    environment:
      VITE_API_BASE: http://api:${API_PORT:-4000}
    ports:
      - "5173:5173"
    volumes:
      - web_data:/app
    depends_on:
      - api

volumes:
  db_data:
  api_data:
  web_data:
