version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - db_data_ns5:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 90s


  api:
    image: node:20-alpine
    working_dir: /app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      API_PORT: ${API_PORT}
      API_JWT_ACCESS_TTL: ${API_JWT_ACCESS_TTL}
      API_JWT_REFRESH_TTL: ${API_JWT_REFRESH_TTL}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_REFRESH_SECRET: ${API_REFRESH_SECRET}
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
      TMDB_API_KEY: ${TMDB_API_KEY}
      NODE_ENV: ${NODE_ENV}
    # On télécharge le repo public, on copie /api, on build et on lance
    command: >
      sh -c "
        apk add --no-cache unzip curl &&
        curl -L https://github.com/SaohTG/Nova-Stream/archive/refs/heads/main.zip -o /tmp/src.zip &&
        unzip -q /tmp/src.zip -d /tmp &&
        cp -r /tmp/Nova-Stream-main/api/. /app &&
        npm ci &&
        npm run build &&
        node dist/main.js
      "
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT:-4000}:4000"
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      # IMPORTANT: URL joignable par le NAVIGATEUR (remplace <IP/DNS> par le tien)
      VITE_API_BASE: http://<IP_OU_DNS_PUBLIC>:${API_PORT:-4000}
    # On télécharge le repo public, on copie /web, on build et on lance le preview
    command: >
      sh -c "
        apk add --no-cache unzip curl &&
        curl -L https://github.com/SaohTG/Nova-Stream/archive/refs/heads/main.zip -o /tmp/src.zip &&
        unzip -q /tmp/src.zip -d /tmp &&
        cp -r /tmp/Nova-Stream-main/web/. /app &&
        npm ci &&
        npm run build &&
        npm run preview -- --host 0.0.0.0 --port 5173
      "
    depends_on:
      - api
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  db_data_ns5: {}
